# open_manipulator:
#   joint_state_controller:
#     type: "joint_state_controller/JointStateController"
#     publish_rate: 1000

# arm_controller:
#   joint1_position:
#     type: position_controllers/JointPositionController
#     joint: joint1

#   joint2_position:
#     type: position_controllers/JointPositionController
#     joint: joint2

#   joint3_position:
#     type: position_controllers/JointPositionController
#     joint: joint3

#   joint4_position:
#     type: position_controllers/JointPositionController
#     joint: joint4

#   joint5_position:
#     type: position_controllers/JointPositionController
#     joint: joint5

#   joint6_position:
#     type: position_controllers/JointPositionController
#     joint: joint6

# gripper_controller:
#   gripper_position:
#     type: effort_controllers/JointPositionController
#     joint: gripper
#     pid: {p: 100, i: 0, d: 0}
#   gripper_sub_position:
#     type: effort_controllers/JointPositionController
#     joint: gripper_sub
#     pid: {p: 100, i: 0, d: 0}

# gazebo_ros_control:
#   pid_gains:
#     joint1:
#       p: 1.0
#       i: 0.0
#       d: 0.0
#     joint2:
#       p: 1.0
#       i: 0.0
#       d: 0.0
#     joint3:
#       p: 1.0
#       i: 0.0
#       d: 0.0
#     joint4:
#       p: 1.0
#       i: 0.0
#       d: 0.0
#     joint5:
#       p: 1.0
#       i: 0.0
#       d: 0.0
#     joint6:
#       p: 1.0
#       i: 0.0
#       d: 0.0
#     gripper:
#       p: 100.0
#       i: 0.0
#       d: 0.0
#     gripper_sub:
#       p: 100.0
#       i: 0.0
#       d: 0.0
      
robomaster:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

right_front_wheel_controller:
  type     : velocity_controllers/JointVelocityController
  joint    : right_front_wheel_joint
  publish_rate: 50
  pid: {p: 10.0, i: 1.0, d: 0.0}

left_front_wheel_controller:
  type     : velocity_controllers/JointVelocityController
  joint    : left_front_wheel_joint
  publish_rate: 50
  pid: {p: 10.0, i: 1.0, d: 0.0}

right_rear_wheel_controller:
  type     : velocity_controllers/JointVelocityController
  joint    : right_rear_wheel_joint
  publish_rate: 50
  pid: {p: 10.0, i: 1.0, d: 0.0}

left_rear_wheel_controller:
  type     : velocity_controllers/JointVelocityController
  joint    : left_rear_wheel_joint
  publish_rate: 50
  pid: {p: 10.0, i: 1.0, d: 0.0}

gazebo_ros_control:
  pid_gains:
    right_front_wheel_joint:
      p: 10.0
      i: 1.0
      d: 0.0
    left_front_wheel_joint:
      p: 10.0
      i: 1.0
      d: 0.0
    right_rear_wheel_joint:
      p: 10.0
      i: 1.0
      d: 0.0
    left_rear_wheel_joint:
      p: 10.0
      i: 1.0
      d: 0.0
